### ISSUE TITLE
Python client misrepresents certain errors

### ISSUE THREAD

**Issue by ryanjoneil** [yhat/yhat-client#1]
This error will be thrown if the server address is mispelled, or if the network is down, etc.

```
  File "/tmp/monitor/py_test_model_Iceman.py", line 6, in <module>
    yh = Yhat("USER", "APIKEY", "SERVER")
  File "/usr/local/lib/python2.7/dist-packages/yhat/api.py", line 174, in __init__
    raise Exception("Incorrect username/apikey!")
Exception: Incorrect username/apikey!
```

Here's where the error is given: https://github.com/yhat/yhat-client/blob/master/yhat/api.py#L230

But the _authenticate method swallows the real error: https://github.com/yhat/yhat-client/blob/master/yhat/api.py#L265-L266

**Comment by rosskipp** [comment]
changing the _post method to use requests makes this error a little better with #13.
