### ISSUE TITLE
Issue w/ open file

### ISSUE THREAD

**Issue by coristig** [yhat/yhat-client#10]
Not sure what this is exactly, will update as I learn more.

Note that this is on a Windows Machine:

![image](https://cloud.githubusercontent.com/assets/7118371/15899873/46b1aea6-2d6b-11e6-8738-53abcd09f9d3.png)

**Comment by rosskipp** [comment]
This seems relevant: http://stackoverflow.com/questions/28396759/os-remove-in-windows-gives-error-32-being-used-by-another-process
